name: CI-backend

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'Backend Build')
    outputs:
      TAG: ${{ steps.extract_tag.outputs.TAG }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
           
      - name: Extract tag from commit message
        id: extract_tag
        run: |
          TAG=$(echo "${{ github.event.head_commit.message }}" | grep -oP 'Backend Build: \s*\K[\w\.]+')
          echo "Extracted tag is $TAG"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_OUTPUT
          
      - name: Create .env file
        working-directory: ./backend
        run: |
          echo "DATABASE_URL=${{ secrets.DB_URL }}" >> .env
          echo "DATABASE_USERNAME=${{ secrets.DB_ID }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DB_PW }}" >> .env
          echo "MAIL_USERNAME=${{ secrets.MAIL_ID }}" >> .env
          echo "MAIL_PASSWORD=${{ secrets.MAIL_PW }}" >> .env

      - name: Build with Gradle
        working-directory: ./backend
        run: ./gradlew clean build
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          push: true
          tags: woya031/ci-ice-back:${{ env.TAG }}

  push:
    name: Push Manifest
    needs: build
    runs-on: ubuntu-latest
    env:
      TAG: ${{ needs.build.outputs.TAG }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          repository: chawoa/Advice_Manifest
          token: ${{ secrets.GH_TOKEN }}

      - name: Change manifest
        run: sed -i "s|woya031/ci-ice-back:[^ ]*|woya031/ci-ice-back:${{ env.TAG }}|" k8s/back-main.yaml

      - name: git push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config credential.helper store
          git add k8s/back-main.yaml
          git commit -m ":tada: Update: Image [${{ env.TAG }}]"
          git push
